version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jktech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start:prod
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: jktech
      JWT_SECRET: secret
    depends_on:
      - db

volumes:
  pgdata:
